### ISSUE TITLE
Issue parsing error trace as exported by toolbox.

### ISSUE THREAD

**Issue by danwt** [japgolly/tla2json#1]
Hi,

I like your tool and I managed to use it successfully on the example file you gave. I tried to run it on .txt file containing the contents of copy-pasting the error-trace from the toolbox (clicking 4th button from right in image below). The output file contains nothing, only '[]\n', e.g. an empty json list. I did try different combinations of command line arguments but none worked. 

Am I doing something wrong or is this kind of output unsupported?

![image](https://user-images.githubusercontent.com/30197399/108527978-d2c4b880-72ca-11eb-84d4-9df577a57a87.png)

**Comment by japgolly** [comment]
Hey @danwt, would you be able to supply that text file that it's not parsing correctly?

**Comment by danwt** [comment]
Hi, I'm sorry for the delayed response. Here is an example.

[trace.txt](https://github.com/japgolly/tla2json/files/6062219/trace.txt)

**Comment by japgolly** [comment]
Hey, thanks for uploading that. Ok, so that content is new to me. I don't use the toolbox GUI and it seems it has it's own formatting style. Are all those keys like `addr`, `addr_`, `addr_c`, `bal`, `chunk_left_wing`, `chunk_of_node` etc, are they all your variables? I'm guessing that `_TEAction` is provided by the toolbox and everything else is yours?

**Comment by danwt** [comment]
Hi, that's exactly right. I will try to use TLC on the command line to generate an error trace instead. 

One suggestion I have would be to add example files to show the expected contents for the various options supported by your tool, e.g. -D -T -S -V -d -f -l. Anyway great tool, thank you.

**Comment by japgolly** [comment]
Ok cool, I've published a new version (1.0.1) that supports error traces exported from the Toolbox. Please give it another try.

> One suggestion I have would be to add example files to show the expected contents for the various options supported by your tool, e.g. -D -T -S -V -d -f -l

That's a good idea. I've got to move on to other things now but I'll keep it in mind for the future.

> Anyway great tool, thank you

Thank you! I'm glad you find it useful :)

**Comment by danwt** [comment]
> , I've published a new version (1.0.1) that supports error traces exported from the Toolbox.

Wow! That's amazing, thank you so much. I should play around with the command line a bit and then maybe I can make a PR with some examples as mentioned.

Looking forward to trying out the new version, cheers.

**Comment by japgolly** [comment]
No worries at all, enjoy!
